Add some features
FHDA/DBImport pull request #13
Opened 2019-09-10 21:07 UTC by biankaiwen111

1. can read .json one by one automatically
2.change __init__ in Course class

2019-09-10 22:57 UTC, yifeili98 commented on ReadCourseData.py
> +	###Don't forget to put all the .json file in the current dir
Consider using more functions to reduce cognitive complexity in main()

2019-09-10 22:58 UTC, yifeili98 commented on ReadCourseData.py
> +import os,inspect
nit: os is imported twice

2019-09-10 23:01 UTC, yifeili98 commented
Consider using semantic commit style (https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716)

2019-09-11 00:56 UTC, yifeili98 requested changes

2019-09-11 00:56 UTC, yifeili98 commented on ReadCourseData.py
> +
nit: redundant empty lines

2019-09-11 00:56 UTC, yifeili98 commented on ReadCourseData.py
> +
nit: redundant empty lines

2019-09-11 00:56 UTC, yifeili98 commented on ReadCourseData.py
> +	client = MongoClient("mongodb+srv://" + username +":" + password + "@fhdatimedb-jjsjm.mongodb.net/test?retryWrites=true&w=majority")
nit: maybe consider to use a .env file

2019-09-11 07:26 UTC, kis87988 commented
Please do `git pull origin master` and then fix all errors

2019-09-19 05:59 UTC, hk-mp5a3 reviewed
nit: do not use "print" in production. using log will be a better practice

2020-01-27 08:00 UTC, closed without merging