Zhirezhixin master
FHDA/DBImport pull request #2
Opened 2019-08-01 03:30 UTC by zhirezhixin

2019-08-01 03:34 UTC, kis87988 commented
Please remember to rebase, the Merge branch commit should not be include.

2019-08-01 03:41 UTC, kis87988 commented
I purpose we should use Semantic Commit Messages.
Refer to https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716
and 
https://github.com/joelparkerhenderson/git_commit_message#begin-with-a-short-summary-line

2019-08-01 03:50 UTC, zhirezhixin commented
咋rebase啊。。搜了下没看懂。。

2019-08-01 03:52 UTC, kis87988 requested changes
Please follow http://google.github.io/styleguide/pyguide.html python style guide.
A string should be either a single quote or double quote but not both. 

Another reference https://www.python.org/dev/peps/pep-0008/

2019-08-01 03:52 UTC, kis87988 commented on ReadCourseData.py
> +	def __init__(self, UID, crn, course_num, section_num,\
Try to use `__init__(**kargs,*args)` style

2019-08-01 03:52 UTC, kis87988 commented on ReadCourseData.py
> +	def __init__(self, UID, days, startTime, endTime, \
same as above

2019-08-01 03:52 UTC, kis87988 commented on ReadCourseData.py
we should remove path out here. This should not be absolutely path

2019-08-01 03:52 UTC, kis87988 commented on ReadCourseData.py
>  	clist = []
meaningful variable

2019-08-01 03:52 UTC, kis87988 commented on ReadCourseData.py
> +	dlist = []
meaningful variable

2019-08-01 03:52 UTC, kis87988 commented on ReadCourseData.py
> +			temp_course = Course(c["CRN"], c["CRN"], c["Crse"], c["Sec"], c["Cmp"], c["Cred"],
try just pass c into the class. kargs should help

2019-08-01 03:52 UTC, kis87988 commented on ReadCourseData.py
> +			interesting_name = temp_dept.deptName + " " + temp_course.course_num + " " + temp_course.course_title
what is `interesting_name` mean?
try to use `"{} {} {}".format(var1,var2,var3)` style

2019-08-03 21:08 UTC, kis87988 commented on ReadCourseData.py
> +	def __init__(self, UID, crn, course_num, section_num,\
since the parameters are too many. we should not list it all out.

2019-08-31 20:22 UTC, kis87988 commented
.env file should not be push to repo.
please reset and force push again. 
.evn should not in any of commit

2019-08-31 22:54 UTC, closed without merging