Implement FHDA logger module
FHDA/DBImport pull request #20
Opened 2020-06-08 01:01 UTC by yifeili98

2020-06-08 01:03 UTC, yifeili98 commented
CC      : (

2020-06-08 01:11 UTC, kis87988 requested changes

2020-06-08 01:11 UTC, kis87988 commented on src/FHDAlogger.py
> +    if level == 'INFO':
If we pass level directly to `basicConfig`, I think it also works, but will get exception

2020-06-08 01:11 UTC, kis87988 commented on src/InsertData.py
> +    raise FileNotFoundError('File ' + filename + ' is not found!')
LOL. We can use f-string

2020-06-08 16:15 UTC, kis87988 commented
LGTM. Let's merge into this repo first. However, I am thinking we will have logger module to a repo. then our product have same format.

2020-06-08 16:16 UTC, kis87988 approved these changes

2020-06-09 01:12 UTC, biankaiwen111 approved these changes
LGTM QAQ

2020-06-09 01:13 UTC, merged